[[scenes]]
id = "lobby_01"
name = "游戏主界面"
logic = "and"

[scenes.anchors]
text = [
]
color = [
]

# --- 跳转动作 ---
[[scenes.transitions]]
target = "next"
coords = [520, 328]
post_delay = 500

[[scenes.transitions]]
target = "next"
coords = [690, 327]
post_delay = 500

[[scenes.transitions]]
target = "next"
coords = [884, 332]
post_delay = 500

[[scenes.transitions]]
target = "next"
coords = [1060, 333]
post_delay = 500

[[scenes.transitions]]
target = "next"
coords = [1229, 323]
post_delay = 500

[[scenes.transitions]]
target = "next"
coords = [518, 536]
post_delay = 500

